export const ADD_APPOINTMENT_SUCCESS = "ADD_APPOINTMENT_SUCCESS"
export const ADD_APPOINTMENT_FAILED = "ADD_APPOINTMENT_FAILED"
export const ADD_APPOINTMENT_LOADING = "ADD_APPOINTMENT_LOADING"



export const GET_ALL_APPOINTMENT_SUCCESS = "GET_ALL_APPOINTMENT_SUCCESS"
export const GET_ALL_APPOINTMENT_FAILED = "GET_ALL_APPOINTMENT_FAILED"
export const GET_ALL_APPOINTMENT_LOADING = "GET_ALL_APPOINTMENT_LOADING"




export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS"
export const DELETE_APPOINTMENT_FAILED = "DELETE_APPOINTMENT_FAILED"
export const DELETE_APPOINTMENT_LOADING = "DELETE_APPOINTMENT_LOADING"


export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS"
export const UPDATE_APPOINTMENT_FAILED = "UPDATE_APPOINTMENT_FAILED"
export const UPDATE_APPOINTMENT_LOADING = "UPDATE_APPOINTMENT_LOADING"



export const GET_APPOINTMENT_SUCCESS = "GET_APPOINTMENT_SUCCESS"
export const GET_APPOINTMENT_FAILED = "GET_APPOINTMENT_FAILED"
export const GET_APPOINTMENT_LOADING = "GET_APPOINTMENT_LOADING"







































