export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGIN_LOADING = "LOGIN_LOADING"


export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const REGISTER_LOADING = "REGISTER_LOADING"

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED"
export const GET_PROFILE_LOADING = "GET_PROFILE_LOADING"

export const LOGOUT = "LOGOUT"


