export const GET_All_USERS_SUCCESS = "GET_All_USERS_SUCCESS"
export const GET_All_USERS_FAILED = "GET_All_USERS_FAILED"
export const GET_All_USERS_LOADING = "GET_All_USERS_LOADING"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILED = "DELETE_USER_FAILED"
export const DELETE_USER_LOADING = "DELETE_USER_LOADING"

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED"
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING"









